import { Stack, Typography } from '@mui/material';
import PrimaryButton from '../ui/primary-button';
import TextArea from '../ui/text-field';
import StepHeader from '../ui/step-header';
import NextButton from '../ui/next-button';
import { useFormik } from 'formik';
import { useState } from 'react';
import generateFakeTopics from '../../../fake-async-actions/more-research';

export default function Step2({ send, selectedTopic, currentState }: any) {

  const [researchText, setResearchText] = useState('');

  const formik = useFormik({
    initialValues: {
      reasearchTopic: ''
    },
    onSubmit: (values) => {
      console.log(values)
      generateFakeTopics().then((value: string) => setResearchText(value));
    }
  });

  const handleNext = () => {
    send({ type: 'NEXT' });
  }

  const handlePrevious = () => {
    send({ type: 'PREVIOUS' });
  }

  return (
    <div>
      <Stack spacing={2}>
        <StepHeader stepHeader='Step 2' />
        <Typography fontWeight={'bold'} className='text-center' variant='h5'>{selectedTopic}</Typography>
        <div className='w-fit'>
          <PrimaryButton onClick={handlePrevious}>Back</PrimaryButton>
        </div>
        <form onSubmit={formik.handleSubmit}>
          <TextArea value={formik.values.reasearchTopic} onChange={formik.handleChange} name='reasearchTopic' placeholder='Enter text (optional)' />
          <div className='w-fit'>
            <PrimaryButton type='submit'>More research</PrimaryButton>
          </div>
        </form>
        {/* here render the list of values that generated by the user */}
        <Typography >
          {researchText}
        </Typography>
        {/* after search complete enable the next button */}
        <div className='w-fit'>
          {
            researchText && <NextButton className='bg-black' onNext={handleNext} disabled={!currentState.matches('step2')}>Next</NextButton>
          }
        </div>
      </Stack>
    </div>
  );
}
